services:

  spring:
    image: eclipse-temurin:21
    working_dir: /workspace
    volumes:
      - ../app:/workspace
    container_name: spring
    command: ./gradlew bootRun --continuous
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ../mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge